name: Build for iOS

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version:'11.7.0'

      - uses: actions/checkout@v2

      - name: RoboVM Build
        run: |
          chmod +x gradlew
          ./gradlew -Probovm.archs=arm64 clean createIPA

      - name: Upload IPA
        uses: actions/upload-artifact@main
        with:
          name: AngleLauncher
          path: build/robovm/AngleLauncher.ipa
